# 服务器
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
# spring配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_xsbd?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  freemarker:
#    suffix: .ftl
# mybatis配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
# pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true